<?php

declare(strict_types=1);

namespace Tests\Feature\Documentation;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * The data dictionary and the ER model must describe the schema that exists.
 *
 * WHY THIS TEST IS THE POINT OF GENERATING THEM AT ALL.
 *
 * A generated document that nobody regenerates is worse than a hand-written
 * one: it carries the authority of being derived from the schema while being
 * just as stale, and nothing on its face says which. These tests are what make
 * the claim true. Add a table or a column without regenerating, and CI fails
 * with the name of the thing you left undocumented.
 *
 * They assert PRESENCE, not prose. The wording in those files is hand written
 * on purpose and must stay free to improve without breaking a test.
 *
 * When one fails, the fix is one command:
 *
 *     php tools/generate-data-docs.php
 */
class DataDocsTest extends TestCase
{
    use RefreshDatabase;

    private function dictionary(): string
    {
        return file_get_contents(base_path('doc/DATA_DICTIONARY.md'));
    }

    private function erModel(): string
    {
        return file_get_contents(base_path('doc/ENTITY_RELATIONSHIP.md'));
    }

    /**
     * Every table, except the framework's own migration ledger.
     *
     * @return list<string>
     */
    private function tables(): array
    {
        return collect(Schema::getTables())
            ->pluck('name')
            ->reject(fn (string $t): bool => $t === 'migrations')
            ->values()
            ->all();
    }

    #[Test]
    public function both_documents_exist(): void
    {
        $this->assertFileExists(base_path('doc/DATA_DICTIONARY.md'));
        $this->assertFileExists(base_path('doc/ENTITY_RELATIONSHIP.md'));
    }

    #[Test]
    public function every_table_is_in_the_data_dictionary(): void
    {
        $dictionary = $this->dictionary();

        foreach ($this->tables() as $table) {
            $this->assertStringContainsString(
                '## `'.$table.'`',
                $dictionary,
                "The table `{$table}` has no entry in doc/DATA_DICTIONARY.md. "
                .'Run: php tools/generate-data-docs.php'
            );
        }
    }

    #[Test]
    public function every_column_is_in_the_data_dictionary(): void
    {
        $dictionary = $this->dictionary();
        $missing = [];

        foreach ($this->tables() as $table) {
            /* The table's own section, so a column name that happens to appear
             * under a different table does not count as documented. */
            $start = strpos($dictionary, '## `'.$table.'`');

            if ($start === false) {
                $missing[] = $table.' (whole table)';

                continue;
            }

            $next = strpos($dictionary, "\n## ", $start + 1);
            $section = substr($dictionary, $start, $next === false ? null : $next - $start);

            foreach (Schema::getColumns($table) as $column) {
                $name = $column['name'];

                if (! str_contains($section, '`'.$name.'`') && ! str_contains($section, '**'.$name.'**')) {
                    $missing[] = $table.'.'.$name;
                }
            }
        }

        $this->assertSame(
            [],
            $missing,
            "These columns exist but are not documented:\n  ".implode("\n  ", $missing)
            ."\nRun: php tools/generate-data-docs.php"
        );
    }

    #[Test]
    public function every_foreign_key_is_in_the_entity_relationship_model(): void
    {
        $er = $this->erModel();
        $missing = [];

        foreach ($this->tables() as $table) {
            foreach (Schema::getForeignKeys($table) as $fk) {
                $column = $fk['columns'][0] ?? '';
                $row = '| `'.$table.'` | `'.$column.'` | `'.$fk['foreign_table'].'` |';

                if (! str_contains($er, $row)) {
                    $missing[] = $table.'.'.$column.' -> '.$fk['foreign_table'];
                }
            }
        }

        $this->assertSame(
            [],
            $missing,
            "These foreign keys exist but are not in the ER model:\n  ".implode("\n  ", $missing)
            ."\nRun: php tools/generate-data-docs.php"
        );
    }

    #[Test]
    public function the_documents_say_they_are_generated(): void
    {
        /*
         * Somebody who opens one of these to fix a typo needs to know their fix
         * will be overwritten. Without this line, generated documentation
         * quietly eats hand edits.
         */
        foreach ([$this->dictionary(), $this->erModel()] as $doc) {
            $this->assertStringContainsString('GENERATED. Do not edit this file by hand.', $doc);
            $this->assertStringContainsString('php tools/generate-data-docs.php', $doc);
        }
    }

    #[Test]
    public function no_table_is_left_without_a_description(): void
    {
        /*
         * The generator emits a placeholder rather than failing, so a new table
         * still appears - but an undescribed table in a data dictionary is a row
         * of types and no information, which is the thing this document exists
         * to be better than.
         */
        $this->assertStringNotContainsString(
            'No description recorded',
            $this->dictionary(),
            'A table has no description. Add one to tools/data-meanings.php, then regenerate.'
        );
    }
}
