-- ============================================================================
-- CONFIRM-MIGRATION-LEDGER.sql
--
-- GENERATED FILE. Do not hand-edit.
--   Generated by : tools/generate-migration-ledger-sql.php
--   From commit  : 660d74c427a9e9dab3d611d39e69396cab5953e9
--   Migrations   : 33
--
-- Regenerate with:
--   php tools/generate-migration-ledger-sql.php <commit-sha>
--
-- SELECT ONLY. No CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, TRUNCATE,
-- GRANT or REVOKE. It cannot change anything.
--
-- WHAT THIS REPLACED, AND WHY. The previous version asserted
-- COUNT(migrations) = 33 and treated that as proof every migration had run.
-- A count is not a set: 33 rows made of (33 minus 1) correct rows plus one
-- obsolete row would have passed while a real migration was still pending.
--
-- This reconciles BOTH directions and names the offenders when either fails.
--
-- Run with the SemantIQ database selected.
-- ============================================================================

SELECT 'K1. every migration on approved main is in the ledger' AS check_name,
       CONCAT(COUNT(*), ' missing') AS observed,
       CASE WHEN COUNT(*) = 0 THEN 'PASS'
            ELSE 'STOP - a migration on main never ran' END AS verdict,
       IFNULL(GROUP_CONCAT(e.migration ORDER BY e.migration SEPARATOR ' | '),
              'none') AS detail
FROM (
      SELECT '0001_01_01_000000_create_users_table' AS migration
      UNION ALL SELECT '0001_01_01_000001_create_cache_table'
      UNION ALL SELECT '0001_01_01_000002_create_jobs_table'
      UNION ALL SELECT '2026_08_23_090000_add_federated_identity_to_users_table'
      UNION ALL SELECT '2026_08_23_100000_add_role_to_users_table'
      UNION ALL SELECT '2026_08_23_110000_align_roles_with_role_model'
      UNION ALL SELECT '2026_08_23_110100_create_domain_entitlements_table'
      UNION ALL SELECT '2026_08_24_090000_create_organisations_table'
      UNION ALL SELECT '2026_08_24_090100_create_audit_events_table'
      UNION ALL SELECT '2026_08_24_090200_create_system_settings_table'
      UNION ALL SELECT '2026_08_24_090300_create_feature_flags_table'
      UNION ALL SELECT '2026_08_25_090000_add_organisation_profile_to_organisations_table'
      UNION ALL SELECT '2026_08_25_090100_create_business_units_table'
      UNION ALL SELECT '2026_08_25_090200_create_teams_table'
      UNION ALL SELECT '2026_08_25_090300_create_roles_table'
      UNION ALL SELECT '2026_08_25_090400_create_role_permissions_table'
      UNION ALL SELECT '2026_08_25_090500_create_user_roles_table'
      UNION ALL SELECT '2026_08_25_090600_add_identity_context_to_users_table'
      UNION ALL SELECT '2026_08_25_090700_create_access_reviews_table'
      UNION ALL SELECT '2026_08_25_090800_create_access_review_items_table'
      UNION ALL SELECT '2026_08_25_090900_seed_built_in_roles'
      UNION ALL SELECT '2026_08_26_090000_create_security_policies_table'
      UNION ALL SELECT '2026_08_26_090100_create_secret_references_table'
      UNION ALL SELECT '2026_08_27_090000_create_personal_data_categories_table'
      UNION ALL SELECT '2026_08_27_090100_create_data_protection_profiles_table'
      UNION ALL SELECT '2026_08_27_090200_create_data_sovereignty_profiles_table'
      UNION ALL SELECT '2026_08_27_090300_add_structured_privacy_contact_to_organisations_table'
      UNION ALL SELECT '2026_08_28_090000_create_sovereignty_exceptions_table'
      UNION ALL SELECT '2026_08_28_090100_create_retention_policies_table'
      UNION ALL SELECT '2026_08_28_090200_add_module_and_outcome_indexes_to_audit_events_table'
      UNION ALL SELECT '2026_08_29_090000_create_privacy_requests_table'
      UNION ALL SELECT '2026_08_29_090100_create_privacy_request_records_table'
      UNION ALL SELECT '2026_08_29_090200_create_privacy_correction_notes_table'
     ) AS e
LEFT JOIN migrations m ON m.migration = e.migration
WHERE m.migration IS NULL

UNION ALL
SELECT 'K2. the ledger holds nothing unexpected',
       CONCAT(COUNT(*), ' unexpected'),
       CASE WHEN COUNT(*) = 0 THEN 'PASS'
            ELSE 'STOP - the ledger holds a row not on approved main' END,
       IFNULL(GROUP_CONCAT(m.migration ORDER BY m.migration SEPARATOR ' | '),
              'none')
FROM migrations m
LEFT JOIN (
      SELECT '0001_01_01_000000_create_users_table' AS migration
      UNION ALL SELECT '0001_01_01_000001_create_cache_table'
      UNION ALL SELECT '0001_01_01_000002_create_jobs_table'
      UNION ALL SELECT '2026_08_23_090000_add_federated_identity_to_users_table'
      UNION ALL SELECT '2026_08_23_100000_add_role_to_users_table'
      UNION ALL SELECT '2026_08_23_110000_align_roles_with_role_model'
      UNION ALL SELECT '2026_08_23_110100_create_domain_entitlements_table'
      UNION ALL SELECT '2026_08_24_090000_create_organisations_table'
      UNION ALL SELECT '2026_08_24_090100_create_audit_events_table'
      UNION ALL SELECT '2026_08_24_090200_create_system_settings_table'
      UNION ALL SELECT '2026_08_24_090300_create_feature_flags_table'
      UNION ALL SELECT '2026_08_25_090000_add_organisation_profile_to_organisations_table'
      UNION ALL SELECT '2026_08_25_090100_create_business_units_table'
      UNION ALL SELECT '2026_08_25_090200_create_teams_table'
      UNION ALL SELECT '2026_08_25_090300_create_roles_table'
      UNION ALL SELECT '2026_08_25_090400_create_role_permissions_table'
      UNION ALL SELECT '2026_08_25_090500_create_user_roles_table'
      UNION ALL SELECT '2026_08_25_090600_add_identity_context_to_users_table'
      UNION ALL SELECT '2026_08_25_090700_create_access_reviews_table'
      UNION ALL SELECT '2026_08_25_090800_create_access_review_items_table'
      UNION ALL SELECT '2026_08_25_090900_seed_built_in_roles'
      UNION ALL SELECT '2026_08_26_090000_create_security_policies_table'
      UNION ALL SELECT '2026_08_26_090100_create_secret_references_table'
      UNION ALL SELECT '2026_08_27_090000_create_personal_data_categories_table'
      UNION ALL SELECT '2026_08_27_090100_create_data_protection_profiles_table'
      UNION ALL SELECT '2026_08_27_090200_create_data_sovereignty_profiles_table'
      UNION ALL SELECT '2026_08_27_090300_add_structured_privacy_contact_to_organisations_table'
      UNION ALL SELECT '2026_08_28_090000_create_sovereignty_exceptions_table'
      UNION ALL SELECT '2026_08_28_090100_create_retention_policies_table'
      UNION ALL SELECT '2026_08_28_090200_add_module_and_outcome_indexes_to_audit_events_table'
      UNION ALL SELECT '2026_08_29_090000_create_privacy_requests_table'
      UNION ALL SELECT '2026_08_29_090100_create_privacy_request_records_table'
      UNION ALL SELECT '2026_08_29_090200_create_privacy_correction_notes_table'
     ) AS e ON e.migration = m.migration
WHERE e.migration IS NULL

UNION ALL SELECT '---', '---', '---', '---'

-- --------------------------------------------------- the three R1.4c-i rows
UNION ALL
SELECT 'K3. the three R1.4c-i migrations recorded, by exact name',
       CONCAT(COUNT(*), ' of 3'),
       CASE WHEN COUNT(*) = 3 THEN 'PASS' ELSE 'STOP' END,
       IFNULL(GROUP_CONCAT(CONCAT(migration, ' [batch ', batch, ']')
                           ORDER BY migration SEPARATOR ' | '), 'none')
FROM migrations
WHERE migration IN (
  '2026_08_29_090000_create_privacy_requests_table',
  '2026_08_29_090100_create_privacy_request_records_table',
  '2026_08_29_090200_create_privacy_correction_notes_table')

UNION ALL
SELECT 'K4. all three landed in ONE batch',
       CONCAT(COUNT(DISTINCT batch), ' distinct batch(es)'),
       CASE WHEN COUNT(*) = 3 AND COUNT(DISTINCT batch) = 1 THEN 'PASS'
            ELSE 'STOP - split across runs, or not all present' END,
       CONCAT('batch ', CAST(IFNULL(MIN(batch), 0) AS CHAR))
FROM migrations
WHERE migration IN (
  '2026_08_29_090000_create_privacy_requests_table',
  '2026_08_29_090100_create_privacy_request_records_table',
  '2026_08_29_090200_create_privacy_correction_notes_table')

UNION ALL
SELECT 'K5. highest batch in the ledger',
       CAST(IFNULL(MAX(batch), 0) AS CHAR),
       'INFO - report the value; it was 6 before this migration',
       'batch numbers are assigned by Laravel per migrate run'
FROM migrations;
