<?php

declare(strict_types=1);

/** Column meanings that are specific to one table. Keyed `table.column`. */
return [
    'users.name' => 'Display name. From the directory on a federated account.',
    'users.email' => 'Work email. Unique, and the identifier a person signs in with.',
    'users.email_verified_at' => 'Framework column. Unused: verification comes from the directory.',
    'users.password' => 'Bcrypt hash, or null. **Null is normal** - a federated account has no password here, which is the point.',
    'users.remember_token' => 'Framework "remember me" token. `activity.remember_me_days` ships at 0, so nothing issues one.',
    'users.entra_object_id' => 'The Microsoft Entra object id linking this account to a directory account. Not a credential.',
    'users.entra_tenant_id' => 'The Entra tenant the account came from. Checked against the allow-list at sign-in.',
    'users.last_signed_in_at' => 'When they last got in. Drives the dormant-account view.',
    'users.role' => 'The platform tier, one of six cumulative values. **A CEILING that nothing raises** - no role, grant or assignment gets past it.',
    'users.is_auditor' => 'The Auditor capability flag. Today understood by `Navigation` only; `Authorization` learns it in R1.4b (decision D2, SEC-DEC-062).',
    'users.business_unit_id' => 'Where they sit in the structure. Optional.',
    'users.team_id' => 'Which team. Optional.',
    'users.user_type' => 'Employee, contractor, service account and so on. Affects expectations, not authority.',
    'users.status' => 'Invited, active, disabled, locked or expired. **Checked in the authorization layer, not only at sign-in** - a live session can outlive the moment somebody was disabled (SEC-DEC-026).',
    'users.authentication_source' => 'How they authenticate: the directory, or a local credential.',
    'users.external_reference_id' => 'The customer\'s own identifier for this person, if they have one.',
    'users.access_start' => 'First day access is valid. Null means no start bound.',
    'users.access_end' => 'Last day access is valid. A contractor past this date is refused, and told so on the Microsoft path (SEC-DEC-032).',

    'organisations.legal_name' => 'The registered name, if it differs from the trading name.',
    'organisations.registration_number' => 'The customer\'s own company or entity registration reference.',
    'organisations.primary_country' => 'ISO 3166-1 alpha-2. Decides which privacy and residency questions apply; does not answer them.',
    'organisations.primary_domain' => 'The email domain the organisation uses.',
    'organisations.default_time_zone' => 'IANA identifier. Stored data stays UTC.',
    'organisations.default_currency' => 'ISO 4217, three letters, uppercased on the way in.',
    'organisations.default_language' => 'Display language preference.',
    'organisations.data_owner' => 'Who is accountable for this organisation\'s data. **A name or a job title, never a login or a key.**',
    'organisations.privacy_contact' => '**Legacy, read-only.** The single free-text field that preceded the structured contact. Kept as the source the R1.4a backfill read from, so a wrong backfill can still be compared against the original. No longer accepted from a form (SEC-DEC-075).',
    'organisations.security_contact' => 'Who to reach about a security question. A name or a role.',
    'organisations.privacy_contact_name' => '**Required.** The designated privacy contact. A name or a job title.',
    'organisations.privacy_contact_email' => '**Required.** Where a data subject or a regulator can reach that person. A shared mailbox is usually better than one person\'s inbox.',
    'organisations.privacy_contact_phone' => 'Optional.',
    'organisations.privacy_contact_role' => 'Optional. For example Data Protection Officer.',

    'audit_events.occurred_at' => 'When it happened, in UTC. Distinct from `created_at`, which is when the row was written.',
    'audit_events.actor_user_id' => 'Who did it. Null for a system action or an unauthenticated attempt.',
    'audit_events.actor_type' => '`user` or `system`.',
    'audit_events.actor_label' => 'The actor as text, captured at the time. Survives the account being deleted, which an id would not.',
    'audit_events.action' => 'The catalogue\'s dotted name, for example `governance.sovereignty_profile.approved`.',
    'audit_events.module' => 'Which module wrote it: Identity, Security, Platform, Governance.',
    'audit_events.resource_type' => 'What kind of thing it happened to.',
    'audit_events.resource_id' => 'Which one. Text, so it can hold a non-integer key.',
    'audit_events.outcome' => 'Succeeded, failed or denied. **A denial is evidence** and is recorded, not swallowed.',
    'audit_events.before_summary' => 'Redacted snapshot before the change. Any key matching the sensitive-fragment list stores `[redacted]` instead of its value.',
    'audit_events.after_summary' => 'Redacted snapshot after the change. **This is why column and key names matter** - a policy stored under an obvious name like `auth.timeout` would record every change as "[redacted] -> [redacted]" (SEC-DEC-044).',
    'audit_events.reason' => 'The written reason, scrubbed. Required on high-risk actions.',
    'audit_events.ip_address' => 'Where the request came from. **Personal data.** From R1.4b it sits behind its own permission, `admin.audit.view_network`, at System Administrator only (SEC-DEC-063).',
    'audit_events.correlation_id' => 'One id per request, carried into the trail, the logs and the response header. An inbound value is accepted only when it is a well-formed UUID.',
    'audit_events.environment' => 'Which environment produced the event.',

    'system_settings.key' => 'Catalogue key. An unknown key throws rather than being stored.',
    'system_settings.value' => 'The override, as text. Cast back by the catalogue\'s declared type.',
    'feature_flags.key' => 'Catalogue key for a capability switch.',
    'feature_flags.enabled' => 'Whether it is on. An undeclared flag reads OFF regardless.',
    'feature_flags.reason' => 'Why it was switched. Kept because a flag nobody can explain is a flag nobody dares turn off.',

    'business_units.parent_id' => 'The unit above this one. Self-referencing; null at the top.',
    'business_units.manager_user_id' => 'Who runs it.',
    'business_units.cost_centre' => 'The customer\'s own cost centre reference.',
    'business_units.country' => 'Where the unit operates.',
    'business_units.effective_from' => 'When it came into being.',
    'business_units.effective_to' => 'When it closed. Null means still open. **Closed rather than deleted**, so history stays readable.',
    'teams.business_unit_id' => 'Which unit the team belongs to.',
    'teams.lead_user_id' => 'Who leads it.',

    'roles.tier' => 'The platform tier this role is meant for. A role cannot lift its holder above their own tier.',
    'roles.is_system' => 'Whether this is one of the six built-in roles. A built-in role cannot be edited or deleted.',
    'role_permissions.permission_key' => 'A key from `PermissionRegistry`. Validated on the way in AND on the way out, so a row that outlived its declaration grants nothing.',
    'role_permissions.granted_by_user_id' => 'Who added this permission to the role.',
    'user_roles.assigned_by_user_id' => 'Who assigned the role. **Nobody may hand out authority they do not hold themselves** (VAL-USER-ELEVATE-001).',
    'domain_entitlements.domain' => 'Which business domain: Executive, Sales, Finance, People, Operations, Customer, Learning.',
    'domain_entitlements.scope' => 'Any narrowing - a region, a legal entity, a cost centre.',
    'domain_entitlements.granted_by_user_id' => 'Who granted it. A domain grant is a separate decision from a tier change, with its own route, form and audit event (SEC-DEC-029).',

    'access_reviews.due_at' => 'When the review must be finished by.',
    'access_reviews.opened_at' => 'When it started.',
    'access_reviews.completed_at' => 'When every item had been decided.',
    'access_reviews.applied_at' => 'When the decisions were carried out. Distinct from completion: deciding and doing are two acts.',
    'access_reviews.opened_by_user_id' => 'Who opened it.',
    'access_review_items.access_review_id' => 'Which review this item belongs to.',
    'access_review_items.user_id' => 'Whose access is being reviewed.',
    'access_review_items.subject_type' => 'What is under review: a role, a tier, an entitlement.',
    'access_review_items.subject_key' => 'Which specific one.',
    'access_review_items.subject_label' => 'The subject as text at the time of the review, so the item still reads correctly after the underlying thing changes.',
    'access_review_items.decision' => 'Keep, revoke, or undecided. **Undecided is never treated as an implicit approval** (SEC-DEC-031).',
    'access_review_items.note' => 'Why the reviewer decided that.',
    'access_review_items.decided_by_user_id' => 'Who decided.',
    'access_review_items.decided_at' => 'When.',
    'access_review_items.applied' => 'Whether the decision has been carried out yet.',

    'security_policies.key' => 'Catalogue key, prefixed `sign_in.`, `activity.` or `api.` - never `auth.` or `session.`, which the audit redactor would swallow.',
    'security_policies.value' => 'The override, as text.',
    'security_policies.reason' => 'Required on a high-risk policy change.',

    'secret_references.reference_type' => 'What kind of thing is held elsewhere. **Named `reference_type`, not `secret_type`** - the latter trips the audit redactor.',
    'secret_references.provider' => 'Where it lives: the server environment, a key vault, a provider console.',
    'secret_references.reference_identifier' => 'How to find it there. A pointer, refused if it looks like a credential itself.',
    'secret_references.purpose' => 'What depends on it. This is what makes an expiry date actionable.',
    'secret_references.environment' => 'Which environment the credential serves.',
    'secret_references.owner_user_id' => 'Who is responsible for rotating it.',
    'secret_references.expires_on' => 'When it lapses. Null means nobody is tracking it, which the screen shows rather than hides.',
    'secret_references.rotation_due_on' => 'When it should be rotated, which is usually sooner than expiry.',
    'secret_references.retired_at' => 'When it stopped being used. Retired, not deleted.',

    'personal_data_categories.classification' => 'Public, internal, confidential or restricted. How much harm disclosure would cause.',
    'personal_data_categories.contains_sensitive' => 'Whether it includes data most regimes treat with extra care - health, finances, biometrics. **A different question from classification**: one is harm, the other is kind.',
    'personal_data_categories.source_tables' => 'JSON list of the tables this category lives in. **The input to the R1.4c collector coverage test**, which fails when a schema table is claimed by no category and named in no exclusion list.',

    'data_protection_profiles.applicable_regime' => 'Which privacy law governs this data. A field, not a constant, so a customer in another jurisdiction needs no code change.',
    'data_protection_profiles.regime_basis' => '**Compliance-owned. Ships empty and SemantIQ will never fill it in.** Why that regime applies: who determined it, when, on what grounds. A plausible sentence generated by software would be a compliance claim nobody made.',
    'data_protection_profiles.privacy_officer_designated' => 'Whether somebody has actually been appointed. **Not inferred from the contact field being filled in** - a name in a box is not an appointment.',
    'data_protection_profiles.breach_notification_due_days' => 'How long there is to notify the regulator. Ships at 3 calendar days (decision D7). A breach record freezes the resolved date at decision time, so editing this later cannot move a deadline somebody is held to.',
    'data_protection_profiles.breach_notification_basis' => '**Compliance-owned. Ships empty**, for the same reason as `regime_basis`.',
    'data_protection_profiles.notes' => 'Anything the fields do not cover.',
    'data_protection_profiles.approved_at' => 'When this version was approved. From that moment it is immutable.',
    'data_protection_profiles.approved_by_user_id' => 'Who approved it. `nullOnDelete`: the approval still happened.',
    'data_protection_profiles.superseded_at' => 'When a later version replaced it.',
    'data_protection_profiles.superseded_by_id' => 'Which version replaced it. Self-referencing.',

    'data_sovereignty_profiles.storage_geography' => 'Where the data itself sits.',
    'data_sovereignty_profiles.processing_geography' => 'Where it is processed, **which is not always where it sits**.',
    'data_sovereignty_profiles.ai_processing_geography' => 'Where prompts, responses and embeddings are processed. `not_determined` until an AI service is provisioned.',
    'data_sovereignty_profiles.backup_geography' => 'Where the backups live. **Its own column on purpose**: backups routinely leave the country the server is in, which moves data across a border without the server moving.',
    'data_sovereignty_profiles.approved_geographies' => 'JSON list of geographies this organisation permits at all. **Named `approved_`, never `authorised_`** - `auth` is a redactor fragment and the value would store as `[redacted]`.',
    'data_sovereignty_profiles.external_replication' => 'Whether data is replicated outside its geography, and how far.',
    'data_sovereignty_profiles.cross_geo_storage' => 'Whether data may be stored outside its geography. **Ships OFF at the database default**, per CLAUDE.md.',
    'data_sovereignty_profiles.cross_geo_processing' => 'Whether it may be processed outside. Ships OFF.',
    'data_sovereignty_profiles.cross_geo_ai' => 'Whether AI may process it outside. Ships OFF.',
    'data_sovereignty_profiles.cross_geo_conversation_history' => 'Whether conversation history may be held outside. Ships OFF.',
    'data_sovereignty_profiles.source_note' => 'Where the values came from. Carries the seed\'s provenance so a reader can tell a confirmed fact from a typed-in one.',
    'data_sovereignty_profiles.evidence_reference' => 'A pointer to proof held elsewhere - a hosting contract, a provider attestation. **Named `evidence_`, never `certification_`**: `cert` is a redactor fragment.',
    'data_sovereignty_profiles.notes' => 'Anything the fields do not cover.',
    'data_sovereignty_profiles.approved_at' => 'When this version was approved. Immutable from then on.',
    'data_sovereignty_profiles.approved_by_user_id' => 'Who approved it.',
    'data_sovereignty_profiles.superseded_at' => 'When a later version replaced it.',
    'data_sovereignty_profiles.superseded_by_id' => 'Which version replaced it. Self-referencing.',

    'sessions.user_id' => 'Whose session. Null for a guest session.',
    'sessions.ip_address' => 'Personal data, were this table in use.',
    'sessions.user_agent' => 'Personal data, were this table in use.',
    'sessions.payload' => 'The serialised session.',
    'sessions.last_activity' => 'Unix timestamp of the last request. What a database-driver idle timeout would read.',
    'password_reset_tokens.email' => 'Who asked for the reset.',
    'password_reset_tokens.token' => 'Hashed. Single use, short lived.',
    'cache.key' => 'Cache key.', 'cache.value' => 'Serialised cached value.', 'cache.expiration' => 'Unix timestamp.',
    'cache_locks.key' => 'Lock name.', 'cache_locks.owner' => 'Who holds it.', 'cache_locks.expiration' => 'Unix timestamp.',
    'jobs.queue' => 'Queue name.', 'jobs.payload' => 'The serialised job.', 'jobs.attempts' => 'How many times it has been tried.',
    'jobs.reserved_at' => 'When a worker took it.', 'jobs.available_at' => 'When it becomes runnable.',
    'failed_jobs.uuid' => 'Unique id for the failure.', 'failed_jobs.connection' => 'Which queue connection.',
    'failed_jobs.exception' => 'The stack trace.', 'failed_jobs.failed_at' => 'When it gave up.',
    'job_batches.total_jobs' => 'Size of the batch.', 'job_batches.pending_jobs' => 'How many remain.',
    'job_batches.failed_jobs' => 'How many failed.', 'job_batches.failed_job_ids' => 'Which ones.',
    'job_batches.options' => 'Batch options.', 'job_batches.cancelled_at' => 'If cancelled, when.',
    'job_batches.finished_at' => 'When it completed.',
    /* ---- sovereignty_exceptions, R1.4b ---- */
    'sovereignty_exceptions.data_sovereignty_profile_id' => 'Which approved profile version this departs from, captured at request time. Comparing against whatever is current later would misread an exception raised against version 1 as though it had been raised against version 3.',
    'sovereignty_exceptions.title' => 'What the exception is, in a line somebody scanning a list will understand.',
    'sovereignty_exceptions.justification' => 'Why it is unavoidable and what was tried instead. **The whole basis on which data is allowed to leave its geography**, and what a reviewer weighs.',
    'sovereignty_exceptions.aspect' => 'Which aspect of the profile it departs from - storage, processing, AI processing, backup, replication. A closed list, because an exception to "some stuff" cannot be reviewed or compared against the profile.',
    'sovereignty_exceptions.requested_geography' => 'Where the data would go. **Named `requested_`, never `authorised_`** - `auth` is an audit-redactor fragment and the value would be stored as `[redacted]` for exactly the change an auditor came to read.',
    'sovereignty_exceptions.scope_note' => 'Which data, and how much. An exception scoped to everything is not an exception.',
    'sovereignty_exceptions.starts_on' => 'When it begins. Null means from the moment of approval.',
    'sovereignty_exceptions.ends_on' => '**Required.** An exception with no end date is a permanent change to the sovereignty position wearing the word "exception". It stops applying on this date by itself, computed on read, with nothing needing to run.',
    'sovereignty_exceptions.requested_by_user_id' => 'Who raised it. Compared against the approver, because a requester never approves their own request.',
    'sovereignty_exceptions.requested_at' => 'When it was raised.',
    'sovereignty_exceptions.decided_by_user_id' => 'Who approved or rejected it. **The service refuses to write this equal to `requested_by_user_id`** - the control the tier split cannot express, since a System Administrator holds both permissions.',
    'sovereignty_exceptions.decided_at' => 'When it was decided.',
    'sovereignty_exceptions.decision_note' => 'Why it was approved or rejected. Required.',
    'sovereignty_exceptions.revoked_by_user_id' => 'Who ended it early. **A different act from rejection**: revoking ends something that was in force, rejecting refuses something that never was, and the trail has to tell them apart.',
    'sovereignty_exceptions.revoked_at' => 'When it was revoked. Takes effect immediately - the next request sees it gone.',
    'sovereignty_exceptions.revocation_reason' => 'Why it was ended early. Required.',

    /* ---- retention_policies, R1.4b ---- */
    'retention_policies.personal_data_category_id' => 'Which category this policy governs. One policy per category: two would be two answers to one question.',
    'retention_policies.retention_months' => 'How long, in months. **NULL means Not Configured** - never "forever", and never the seven years this repository once applied to everything. Compliance-owned; SemantIQ ships it empty.',
    'retention_policies.basis' => 'Why that long - the obligation, guidance or contract it comes from. **Compliance-owned and ships empty.** A plausible sentence written by software would be a compliance claim nobody made.',
    'retention_policies.lawful_basis' => 'Which legal ground the data is held under. Also compliance-owned, also empty.',
    'retention_policies.start_event' => '**When the clock starts.** Without this a period is unusable: "three years" from account closure and from record creation are different dates, often years apart.',
    'retention_policies.disposal_action' => 'What happens at the end - review, anonymise, archive, delete, retain. **Recorded as an intention. Nothing in SemantIQ carries it out.**',
    'retention_policies.owner' => 'Who is accountable for this category. A name or a job title, never a login or a key.',
    'retention_policies.exception_rule' => 'Anything overriding the period - a legal hold, a dispute, a regulatory obligation. Free text because the shape of an exception is not knowable in advance; its existence is what the screen surfaces.',
    'retention_policies.next_review_on' => 'When somebody should look again. The screen flags it once the date passes, derived on read. Nothing else happens.',
    'retention_policies.approved_at' => 'When a person agreed the period. **Approving switches nothing on.** Editing afterwards returns the policy to draft, because a period that changed after approval is not the period anybody approved.',
    'retention_policies.approved_by_user_id' => 'Who agreed it.',

    /* PDPA-01 Privacy Requests. Gate 4 batch R1.4c-i. */
    'privacy_requests.reference' => 'Quotable in correspondence: PR-0001. Derived from the highest existing reference rather than a count, so a deleted row can never cause one to be reused - a reference that pointed at two different requests would be worse than none.',
    'privacy_requests.request_type' => 'access, correction or withdrawal. Only the last two route through a decision step; an access request is answered by disclosing.',
    'privacy_requests.subject_user_id' => 'The requester\'s SemantIQ account, if they have one. **Nullable by decision D6**: a person whose account was deleted still has personal data in `audit_events` and is still entitled to ask for it.',
    'privacy_requests.subject_name' => 'Their name, held here rather than read from `users`, so the request survives the deletion of the account it was about.',
    'privacy_requests.subject_email' => 'How they were contacted. Also what `password_reset_tokens` is matched on, since that table is keyed by address rather than by account.',
    'privacy_requests.subject_reference' => 'An external identifier, where the customer uses one. Optional.',
    'privacy_requests.received_at' => 'When the request arrived, which may predate this row - a letter recorded a week later is still received on the day it arrived.',
    'privacy_requests.received_channel' => 'How it arrived: email, post, in person. Free text because the ways a person can ask are not enumerable.',
    'privacy_requests.identity_verified_at' => '**The gate.** Null means unverified, and unverified means nothing is collected. Checked by the service independently of `status`, because a status records where a row got to and a timestamp records that a person actually did something.',
    'privacy_requests.identity_verified_by_user_id' => 'Who confirmed it. The accountable human, not a system.',
    'privacy_requests.identity_verification_method' => 'From the codified list in `config/governance.php`, so "how was this person identified" is comparable across requests rather than a sentence somebody typed.',
    'privacy_requests.identity_verification_note' => 'What was actually checked. Required. "Verified" without this is somebody\'s word for it.',
    'privacy_requests.assembled_at' => 'When collection last ran. Re-running replaces the records wholesale rather than appending, so a response never mixes what was true then with what is true now.',
    'privacy_requests.reviewed_at' => 'When a reviewer went through the assembled response.',
    'privacy_requests.reviewed_by_user_id' => 'Who reviewed it.',
    'privacy_requests.decision' => 'released or refused. Refusal is a lawful outcome, not a failure.',
    'privacy_requests.decision_reason' => 'Required on refusal. Refusing is defensible; refusing without a stated reason is not.',
    'privacy_requests.released_at' => 'When disclosure was authorised. A different act from assembling the response, behind its own permission at System Administrator.',
    'privacy_requests.released_by_user_id' => 'Who authorised it. Deliberately capable of being a different person from whoever assembled it.',
    'privacy_requests.evidence_reference' => 'How the response was actually delivered - a postal tracking number, a meeting date. **SemantIQ sends nothing itself** (D9), so without this there is no evidence the person ever received an answer.',
    'privacy_requests.closed_at' => 'When it was finished. A closed request is never reopened; a new one is raised instead, so the record of what was disclosed on a date stays exactly as it was.',
    'privacy_requests.due_at' => '**Frozen at verification, never recomputed.** A deadline derived from a policy somebody later edited would silently move a date a person is being held to. Whether it has passed IS derived on read, so nothing needs to run.',

    'privacy_request_records.privacy_request_id' => 'Which request this belongs to. Cascade is correct here and only here: these rows have no meaning apart from their request, and the evidence that an assembly happened lives in the audit trail.',
    'privacy_request_records.band' => 'A, B, C or D. How this item relates to the subject, which decides the default treatment. **Band C is the design problem**: the subject\'s name on somebody else\'s record is personal data about two people.',
    'privacy_request_records.source_table' => 'Which table it came from. What the coverage test reconciles against the live schema.',
    'privacy_request_records.collector' => 'The collector class that produced it. Recorded so a reader can find the code that made a disclosure decision.',
    'privacy_request_records.treatment' => 'include, describe or exclude. **`exclude` rows are kept precisely because they disclose nothing** - they are the evidence that a table was considered and deliberately withheld, which is what makes the coverage claim checkable rather than asserted.',
    'privacy_request_records.summary' => 'What the subject is told, already rendered. For band C it was rendered by a function that never received the other person\'s identity, so a template mistake cannot leak what was never passed in.',
    'privacy_request_records.detail' => 'The verbatim structured payload. **Populated only for `include`** - `CollectedItem` refuses the other combination at construction, so no collector can produce a described item that discloses.',
    'privacy_request_records.occurred_at' => 'When the underlying thing happened, for the time-ordered bands.',
    'privacy_request_records.reviewer_action' => 'kept, narrowed or widened. **Widening needs a second approver who is not the reviewer**; narrowing does not. Being more careful is always one person\'s call.',
    'privacy_request_records.reviewer_note' => 'Why a treatment was changed. Required, so nobody can later ask whether a disclosure was considered or accidental.',

    'privacy_correction_notes.privacy_request_id' => 'The request this dispute arose in.',
    'privacy_correction_notes.audit_event_id' => 'The disputed entry. **restrictOnDelete, not cascade**: an annotation must not vanish because something upstream was removed. Nullable, because a subject may dispute something that is not a single event.',
    'privacy_correction_notes.subject_assertion' => 'What the person says is wrong, in their own terms. Written once and never editable, which is the entire point - a dispute the disputed party can rewrite is not evidence of anything.',
    'privacy_correction_notes.outcome' => 'noted, applied or refused. **`noted` is a complete and correct outcome**, not a lesser one: where the disputed record is an audit event, the trail cannot be edited and the permanent annotation beside it IS the remedy.',
    'privacy_correction_notes.outcome_reason' => 'Why this outcome was reached. Required on every outcome including a correction, because "corrected" alone does not say what was corrected or on what basis.',
    'privacy_correction_notes.decided_by_user_id' => 'Who decided.',
    'privacy_correction_notes.decided_at' => 'When. Written with the row, since assertion and decision are recorded together - recording one and then the other would mean updating, and this table cannot be updated.',

    /* Framework queue tables. Empty on this deployment - QUEUE_CONNECTION is
     * sync and there is no worker - but documented because the columns exist
     * and a reader finding them should not have to guess. */
    'failed_jobs.queue' => 'Which queue the job was on when it failed. Framework column.',
    'failed_jobs.payload' => 'The serialised job. **May incidentally contain personal data** if a queued job ever carried any, which is why `failed_jobs` is named in the privacy exclusion register as a known incidental surface rather than silently ignored. Empty on this deployment.',

    'privacy_requests.assembled_by_user_id' => 'Who ran the collection. **Recorded so separation of duties can be enforced against the person who actually did the work, not against a permission tier.** A System Administrator holds both `.manage` and `.release`, so the tier split alone stopped nobody from assembling a response and then authorising its own disclosure. The service compares this and `reviewed_by_user_id` against the releaser.',
];
