<?php

declare(strict_types=1);

/** Column meanings that are specific to one table. Keyed `table.column`. */
return [
    'users.name' => 'Display name. From the directory on a federated account.',
    'users.email' => 'Work email. Unique, and the identifier a person signs in with.',
    'users.email_verified_at' => 'Framework column. Unused: verification comes from the directory.',
    'users.password' => 'Bcrypt hash, or null. **Null is normal** - a federated account has no password here, which is the point.',
    'users.remember_token' => 'Framework "remember me" token. `activity.remember_me_days` ships at 0, so nothing issues one.',
    'users.entra_object_id' => 'The Microsoft Entra object id linking this account to a directory account. Not a credential.',
    'users.entra_tenant_id' => 'The Entra tenant the account came from. Checked against the allow-list at sign-in.',
    'users.last_signed_in_at' => 'When they last got in. Drives the dormant-account view.',
    'users.role' => 'The platform tier, one of six cumulative values. **A CEILING that nothing raises** - no role, grant or assignment gets past it.',
    'users.is_auditor' => 'The Auditor capability flag. Today understood by `Navigation` only; `Authorization` learns it in R1.4b (decision D2, SEC-DEC-062).',
    'users.business_unit_id' => 'Where they sit in the structure. Optional.',
    'users.team_id' => 'Which team. Optional.',
    'users.user_type' => 'Employee, contractor, service account and so on. Affects expectations, not authority.',
    'users.status' => 'Invited, active, disabled, locked or expired. **Checked in the authorization layer, not only at sign-in** - a live session can outlive the moment somebody was disabled (SEC-DEC-026).',
    'users.authentication_source' => 'How they authenticate: the directory, or a local credential.',
    'users.external_reference_id' => 'The customer\'s own identifier for this person, if they have one.',
    'users.access_start' => 'First day access is valid. Null means no start bound.',
    'users.access_end' => 'Last day access is valid. A contractor past this date is refused, and told so on the Microsoft path (SEC-DEC-032).',

    'organisations.legal_name' => 'The registered name, if it differs from the trading name.',
    'organisations.registration_number' => 'The customer\'s own company or entity registration reference.',
    'organisations.primary_country' => 'ISO 3166-1 alpha-2. Decides which privacy and residency questions apply; does not answer them.',
    'organisations.primary_domain' => 'The email domain the organisation uses.',
    'organisations.default_time_zone' => 'IANA identifier. Stored data stays UTC.',
    'organisations.default_currency' => 'ISO 4217, three letters, uppercased on the way in.',
    'organisations.default_language' => 'Display language preference.',
    'organisations.data_owner' => 'Who is accountable for this organisation\'s data. **A name or a job title, never a login or a key.**',
    'organisations.privacy_contact' => '**Legacy, read-only.** The single free-text field that preceded the structured contact. Kept as the source the R1.4a backfill read from, so a wrong backfill can still be compared against the original. No longer accepted from a form (SEC-DEC-075).',
    'organisations.security_contact' => 'Who to reach about a security question. A name or a role.',
    'organisations.privacy_contact_name' => '**Required.** The designated privacy contact. A name or a job title.',
    'organisations.privacy_contact_email' => '**Required.** Where a data subject or a regulator can reach that person. A shared mailbox is usually better than one person\'s inbox.',
    'organisations.privacy_contact_phone' => 'Optional.',
    'organisations.privacy_contact_role' => 'Optional. For example Data Protection Officer.',

    'audit_events.occurred_at' => 'When it happened, in UTC. Distinct from `created_at`, which is when the row was written.',
    'audit_events.actor_user_id' => 'Who did it. Null for a system action or an unauthenticated attempt.',
    'audit_events.actor_type' => '`user` or `system`.',
    'audit_events.actor_label' => 'The actor as text, captured at the time. Survives the account being deleted, which an id would not.',
    'audit_events.action' => 'The catalogue\'s dotted name, for example `governance.sovereignty_profile.approved`.',
    'audit_events.module' => 'Which module wrote it: Identity, Security, Platform, Governance.',
    'audit_events.resource_type' => 'What kind of thing it happened to.',
    'audit_events.resource_id' => 'Which one. Text, so it can hold a non-integer key.',
    'audit_events.outcome' => 'Succeeded, failed or denied. **A denial is evidence** and is recorded, not swallowed.',
    'audit_events.before_summary' => 'Redacted snapshot before the change. Any key matching the sensitive-fragment list stores `[redacted]` instead of its value.',
    'audit_events.after_summary' => 'Redacted snapshot after the change. **This is why column and key names matter** - a policy stored under an obvious name like `auth.timeout` would record every change as "[redacted] -> [redacted]" (SEC-DEC-044).',
    'audit_events.reason' => 'The written reason, scrubbed. Required on high-risk actions.',
    'audit_events.ip_address' => 'Where the request came from. **Personal data.** From R1.4b it sits behind its own permission, `admin.audit.view_network`, at System Administrator only (SEC-DEC-063).',
    'audit_events.correlation_id' => 'One id per request, carried into the trail, the logs and the response header. An inbound value is accepted only when it is a well-formed UUID.',
    'audit_events.environment' => 'Which environment produced the event.',

    'system_settings.key' => 'Catalogue key. An unknown key throws rather than being stored.',
    'system_settings.value' => 'The override, as text. Cast back by the catalogue\'s declared type.',
    'feature_flags.key' => 'Catalogue key for a capability switch.',
    'feature_flags.enabled' => 'Whether it is on. An undeclared flag reads OFF regardless.',
    'feature_flags.reason' => 'Why it was switched. Kept because a flag nobody can explain is a flag nobody dares turn off.',

    'business_units.parent_id' => 'The unit above this one. Self-referencing; null at the top.',
    'business_units.manager_user_id' => 'Who runs it.',
    'business_units.cost_centre' => 'The customer\'s own cost centre reference.',
    'business_units.country' => 'Where the unit operates.',
    'business_units.effective_from' => 'When it came into being.',
    'business_units.effective_to' => 'When it closed. Null means still open. **Closed rather than deleted**, so history stays readable.',
    'teams.business_unit_id' => 'Which unit the team belongs to.',
    'teams.lead_user_id' => 'Who leads it.',

    'roles.tier' => 'The platform tier this role is meant for. A role cannot lift its holder above their own tier.',
    'roles.is_system' => 'Whether this is one of the six built-in roles. A built-in role cannot be edited or deleted.',
    'role_permissions.permission_key' => 'A key from `PermissionRegistry`. Validated on the way in AND on the way out, so a row that outlived its declaration grants nothing.',
    'role_permissions.granted_by_user_id' => 'Who added this permission to the role.',
    'user_roles.assigned_by_user_id' => 'Who assigned the role. **Nobody may hand out authority they do not hold themselves** (VAL-USER-ELEVATE-001).',
    'domain_entitlements.domain' => 'Which business domain: Executive, Sales, Finance, People, Operations, Customer, Learning.',
    'domain_entitlements.scope' => 'Any narrowing - a region, a legal entity, a cost centre.',
    'domain_entitlements.granted_by_user_id' => 'Who granted it. A domain grant is a separate decision from a tier change, with its own route, form and audit event (SEC-DEC-029).',

    'access_reviews.due_at' => 'When the review must be finished by.',
    'access_reviews.opened_at' => 'When it started.',
    'access_reviews.completed_at' => 'When every item had been decided.',
    'access_reviews.applied_at' => 'When the decisions were carried out. Distinct from completion: deciding and doing are two acts.',
    'access_reviews.opened_by_user_id' => 'Who opened it.',
    'access_review_items.access_review_id' => 'Which review this item belongs to.',
    'access_review_items.user_id' => 'Whose access is being reviewed.',
    'access_review_items.subject_type' => 'What is under review: a role, a tier, an entitlement.',
    'access_review_items.subject_key' => 'Which specific one.',
    'access_review_items.subject_label' => 'The subject as text at the time of the review, so the item still reads correctly after the underlying thing changes.',
    'access_review_items.decision' => 'Keep, revoke, or undecided. **Undecided is never treated as an implicit approval** (SEC-DEC-031).',
    'access_review_items.note' => 'Why the reviewer decided that.',
    'access_review_items.decided_by_user_id' => 'Who decided.',
    'access_review_items.decided_at' => 'When.',
    'access_review_items.applied' => 'Whether the decision has been carried out yet.',

    'security_policies.key' => 'Catalogue key, prefixed `sign_in.`, `activity.` or `api.` - never `auth.` or `session.`, which the audit redactor would swallow.',
    'security_policies.value' => 'The override, as text.',
    'security_policies.reason' => 'Required on a high-risk policy change.',

    'secret_references.reference_type' => 'What kind of thing is held elsewhere. **Named `reference_type`, not `secret_type`** - the latter trips the audit redactor.',
    'secret_references.provider' => 'Where it lives: the server environment, a key vault, a provider console.',
    'secret_references.reference_identifier' => 'How to find it there. A pointer, refused if it looks like a credential itself.',
    'secret_references.purpose' => 'What depends on it. This is what makes an expiry date actionable.',
    'secret_references.environment' => 'Which environment the credential serves.',
    'secret_references.owner_user_id' => 'Who is responsible for rotating it.',
    'secret_references.expires_on' => 'When it lapses. Null means nobody is tracking it, which the screen shows rather than hides.',
    'secret_references.rotation_due_on' => 'When it should be rotated, which is usually sooner than expiry.',
    'secret_references.retired_at' => 'When it stopped being used. Retired, not deleted.',

    'personal_data_categories.classification' => 'Public, internal, confidential or restricted. How much harm disclosure would cause.',
    'personal_data_categories.contains_sensitive' => 'Whether it includes data most regimes treat with extra care - health, finances, biometrics. **A different question from classification**: one is harm, the other is kind.',
    'personal_data_categories.source_tables' => 'JSON list of the tables this category lives in. **The input to the R1.4c collector coverage test**, which fails when a schema table is claimed by no category and named in no exclusion list.',

    'data_protection_profiles.applicable_regime' => 'Which privacy law governs this data. A field, not a constant, so a customer in another jurisdiction needs no code change.',
    'data_protection_profiles.regime_basis' => '**Compliance-owned. Ships empty and SemantIQ will never fill it in.** Why that regime applies: who determined it, when, on what grounds. A plausible sentence generated by software would be a compliance claim nobody made.',
    'data_protection_profiles.privacy_officer_designated' => 'Whether somebody has actually been appointed. **Not inferred from the contact field being filled in** - a name in a box is not an appointment.',
    'data_protection_profiles.breach_notification_due_days' => 'How long there is to notify the regulator. Ships at 3 calendar days (decision D7). A breach record freezes the resolved date at decision time, so editing this later cannot move a deadline somebody is held to.',
    'data_protection_profiles.breach_notification_basis' => '**Compliance-owned. Ships empty**, for the same reason as `regime_basis`.',
    'data_protection_profiles.notes' => 'Anything the fields do not cover.',
    'data_protection_profiles.approved_at' => 'When this version was approved. From that moment it is immutable.',
    'data_protection_profiles.approved_by_user_id' => 'Who approved it. `nullOnDelete`: the approval still happened.',
    'data_protection_profiles.superseded_at' => 'When a later version replaced it.',
    'data_protection_profiles.superseded_by_id' => 'Which version replaced it. Self-referencing.',

    'data_sovereignty_profiles.storage_geography' => 'Where the data itself sits.',
    'data_sovereignty_profiles.processing_geography' => 'Where it is processed, **which is not always where it sits**.',
    'data_sovereignty_profiles.ai_processing_geography' => 'Where prompts, responses and embeddings are processed. `not_determined` until an AI service is provisioned.',
    'data_sovereignty_profiles.backup_geography' => 'Where the backups live. **Its own column on purpose**: backups routinely leave the country the server is in, which moves data across a border without the server moving.',
    'data_sovereignty_profiles.approved_geographies' => 'JSON list of geographies this organisation permits at all. **Named `approved_`, never `authorised_`** - `auth` is a redactor fragment and the value would store as `[redacted]`.',
    'data_sovereignty_profiles.external_replication' => 'Whether data is replicated outside its geography, and how far.',
    'data_sovereignty_profiles.cross_geo_storage' => 'Whether data may be stored outside its geography. **Ships OFF at the database default**, per CLAUDE.md.',
    'data_sovereignty_profiles.cross_geo_processing' => 'Whether it may be processed outside. Ships OFF.',
    'data_sovereignty_profiles.cross_geo_ai' => 'Whether AI may process it outside. Ships OFF.',
    'data_sovereignty_profiles.cross_geo_conversation_history' => 'Whether conversation history may be held outside. Ships OFF.',
    'data_sovereignty_profiles.source_note' => 'Where the values came from. Carries the seed\'s provenance so a reader can tell a confirmed fact from a typed-in one.',
    'data_sovereignty_profiles.evidence_reference' => 'A pointer to proof held elsewhere - a hosting contract, a provider attestation. **Named `evidence_`, never `certification_`**: `cert` is a redactor fragment.',
    'data_sovereignty_profiles.notes' => 'Anything the fields do not cover.',
    'data_sovereignty_profiles.approved_at' => 'When this version was approved. Immutable from then on.',
    'data_sovereignty_profiles.approved_by_user_id' => 'Who approved it.',
    'data_sovereignty_profiles.superseded_at' => 'When a later version replaced it.',
    'data_sovereignty_profiles.superseded_by_id' => 'Which version replaced it. Self-referencing.',

    'sessions.user_id' => 'Whose session. Null for a guest session.',
    'sessions.ip_address' => 'Personal data, were this table in use.',
    'sessions.user_agent' => 'Personal data, were this table in use.',
    'sessions.payload' => 'The serialised session.',
    'sessions.last_activity' => 'Unix timestamp of the last request. What a database-driver idle timeout would read.',
    'password_reset_tokens.email' => 'Who asked for the reset.',
    'password_reset_tokens.token' => 'Hashed. Single use, short lived.',
    'cache.key' => 'Cache key.', 'cache.value' => 'Serialised cached value.', 'cache.expiration' => 'Unix timestamp.',
    'cache_locks.key' => 'Lock name.', 'cache_locks.owner' => 'Who holds it.', 'cache_locks.expiration' => 'Unix timestamp.',
    'jobs.queue' => 'Queue name.', 'jobs.payload' => 'The serialised job.', 'jobs.attempts' => 'How many times it has been tried.',
    'jobs.reserved_at' => 'When a worker took it.', 'jobs.available_at' => 'When it becomes runnable.',
    'failed_jobs.uuid' => 'Unique id for the failure.', 'failed_jobs.connection' => 'Which queue connection.',
    'failed_jobs.exception' => 'The stack trace.', 'failed_jobs.failed_at' => 'When it gave up.',
    'job_batches.total_jobs' => 'Size of the batch.', 'job_batches.pending_jobs' => 'How many remain.',
    'job_batches.failed_jobs' => 'How many failed.', 'job_batches.failed_job_ids' => 'Which ones.',
    'job_batches.options' => 'Batch options.', 'job_batches.cancelled_at' => 'If cancelled, when.',
    'job_batches.finished_at' => 'When it completed.',
];
