<?php

declare(strict_types=1);

/**
 * Generate CONFIRM-MIGRATION-LEDGER.sql from an exact git commit.
 *
 * WHY THIS EXISTS. The first version of that script asserted
 * `COUNT(migrations) = 33` and called it proof that all 33 migrations on main
 * had run. It is not. Thirty-two correct rows plus one obsolete row also
 * totals 33, and that state would have passed while a real migration was still
 * pending.
 *
 * A COUNT IS NOT A SET. The replacement reconciles both directions:
 * everything expected is present, and nothing unexpected is present.
 *
 * THE EXPECTED LIST IS NEVER TYPED. It is read from
 * `git ls-tree <sha> database/migrations/` at the approved commit, so it cannot
 * drift from the repository and cannot be mis-remembered. Three times on this
 * project a verification script made a correct production system look broken,
 * every time because an expectation was written from memory instead of read
 * from the source. This removes the opportunity.
 *
 * Usage:  php tools/generate-migration-ledger-sql.php <commit-sha>
 */
$sha = $argv[1] ?? null;

if ($sha === null || ! preg_match('/^[0-9a-f]{7,40}$/', $sha)) {
    fwrite(STDERR, "Usage: php tools/generate-migration-ledger-sql.php <commit-sha>\n");
    exit(1);
}

/* Read the tree at that exact commit, not the working directory. */
exec('git ls-tree --name-only '.escapeshellarg($sha).' database/migrations/ 2>&1', $out, $code);

if ($code !== 0) {
    fwrite(STDERR, "git ls-tree failed:\n".implode("\n", $out)."\n");
    exit(1);
}

$names = [];

foreach ($out as $path) {
    if (! str_ends_with($path, '.php')) {
        continue;
    }

    /* Laravel records the file's basename without the .php extension. */
    $names[] = basename($path, '.php');
}

sort($names);

if ($names === []) {
    fwrite(STDERR, "No migrations found at {$sha}. Refusing to write an empty expectation.\n");
    exit(1);
}

foreach ($names as $name) {
    if (! preg_match('/^[A-Za-z0-9_]+$/', $name)) {
        fwrite(STDERR, "Refusing to emit an unexpected migration name: {$name}\n");
        exit(1);
    }
}

$total = count($names);

/* The expected set as a derived table. No CTE: the production server version
 * is not known from here, and a derived table works on every version that
 * runs this application. */
/*
 * THE FIRST SELECT MUST CARRY THE COLUMN ALIAS. A derived table takes its
 * column names from the first branch of the UNION, so without `AS migration`
 * the join condition `e.migration` does not resolve and the whole script
 * errors. Caught by running the generated logic against a real database
 * rather than reading it and assuming.
 */
$quoted = array_map(static fn (string $n): string => "'".$n."'", $names);
$first = array_shift($quoted);

$expected = 'SELECT '.$first.' AS migration';

foreach ($quoted as $q) {
    $expected .= "\n      UNION ALL SELECT ".$q;
}

$sql = <<<SQL
-- ============================================================================
-- CONFIRM-MIGRATION-LEDGER.sql
--
-- GENERATED FILE. Do not hand-edit.
--   Generated by : tools/generate-migration-ledger-sql.php
--   From commit  : {$sha}
--   Migrations   : {$total}
--
-- Regenerate with:
--   php tools/generate-migration-ledger-sql.php <commit-sha>
--
-- SELECT ONLY. No CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, TRUNCATE,
-- GRANT or REVOKE. It cannot change anything.
--
-- WHAT THIS REPLACED, AND WHY. The previous version asserted
-- COUNT(migrations) = {$total} and treated that as proof every migration had run.
-- A count is not a set: {$total} rows made of ({$total} minus 1) correct rows plus one
-- obsolete row would have passed while a real migration was still pending.
--
-- This reconciles BOTH directions and names the offenders when either fails.
--
-- Run with the SemantIQ database selected.
-- ============================================================================

SELECT 'K1. every migration on approved main is in the ledger' AS check_name,
       CONCAT(COUNT(*), ' missing') AS observed,
       CASE WHEN COUNT(*) = 0 THEN 'PASS'
            ELSE 'STOP - a migration on main never ran' END AS verdict,
       IFNULL(GROUP_CONCAT(e.migration ORDER BY e.migration SEPARATOR ' | '),
              'none') AS detail
FROM (
      {$expected}
     ) AS e
LEFT JOIN migrations m ON m.migration = e.migration
WHERE m.migration IS NULL

UNION ALL
SELECT 'K2. the ledger holds nothing unexpected',
       CONCAT(COUNT(*), ' unexpected'),
       CASE WHEN COUNT(*) = 0 THEN 'PASS'
            ELSE 'STOP - the ledger holds a row not on approved main' END,
       IFNULL(GROUP_CONCAT(m.migration ORDER BY m.migration SEPARATOR ' | '),
              'none')
FROM migrations m
LEFT JOIN (
      {$expected}
     ) AS e ON e.migration = m.migration
WHERE e.migration IS NULL

UNION ALL SELECT '---', '---', '---', '---'

-- --------------------------------------------------- the three R1.4c-i rows
UNION ALL
SELECT 'K3. the three R1.4c-i migrations recorded, by exact name',
       CONCAT(COUNT(*), ' of 3'),
       CASE WHEN COUNT(*) = 3 THEN 'PASS' ELSE 'STOP' END,
       IFNULL(GROUP_CONCAT(CONCAT(migration, ' [batch ', batch, ']')
                           ORDER BY migration SEPARATOR ' | '), 'none')
FROM migrations
WHERE migration IN (
  '2026_08_29_090000_create_privacy_requests_table',
  '2026_08_29_090100_create_privacy_request_records_table',
  '2026_08_29_090200_create_privacy_correction_notes_table')

UNION ALL
SELECT 'K4. all three landed in ONE batch',
       CONCAT(COUNT(DISTINCT batch), ' distinct batch(es)'),
       CASE WHEN COUNT(*) = 3 AND COUNT(DISTINCT batch) = 1 THEN 'PASS'
            ELSE 'STOP - split across runs, or not all present' END,
       CONCAT('batch ', CAST(IFNULL(MIN(batch), 0) AS CHAR))
FROM migrations
WHERE migration IN (
  '2026_08_29_090000_create_privacy_requests_table',
  '2026_08_29_090100_create_privacy_request_records_table',
  '2026_08_29_090200_create_privacy_correction_notes_table')

UNION ALL
SELECT 'K5. highest batch in the ledger',
       CAST(IFNULL(MAX(batch), 0) AS CHAR),
       'INFO - report the value; it was 6 before this migration',
       'batch numbers are assigned by Laravel per migrate run'
FROM migrations;
SQL;

file_put_contents(__DIR__.'/../doc/execution/CONFIRM-MIGRATION-LEDGER.sql', $sql."\n");

fwrite(STDOUT, "Generated from {$sha}: {$total} migrations\n");
