<?php

declare(strict_types=1);

/**
 * Renders doc/DATA_DICTIONARY.md. Included by generate-data-docs.php, which
 * supplies $tables, $live, $foreignKeys, $meanings, $columnMeanings, $byModule,
 * $firstSeen, $generatedFrom and $root.
 */
$out = [];
$out[] = '# SemantIQ Data Dictionary';
$out[] = '';
$out[] = '**GENERATED. Do not edit this file by hand.**';
$out[] = '';
$out[] = 'Regenerate with:';
$out[] = '';
$out[] = '```text';
$out[] = 'php tools/generate-data-docs.php';
$out[] = '```';
$out[] = '';
$out[] = 'Structure comes from `database/migrations/`, which CLAUDE.md names as the';
$out[] = 'source of truth for the schema. Existence, keys and indexes come from the live';
$out[] = 'database. The two are cross-checked and the generator REFUSES TO WRITE if they';
$out[] = 'disagree, so a column documented here is a column that exists.';
$out[] = '';
$out[] = 'Meaning comes from `tools/data-column-meanings.php` and `tools/data-meanings.php`,';
$out[] = 'which are hand written. That is the one part no machine can supply, and it is';
$out[] = 'the part worth reading.';
$out[] = '';
$out[] = 'Types are shown as **MySQL** produces them, because production is MySQL.';
$out[] = '';
$out[] = 'Covers '.$generatedFrom.'.';
$out[] = '';
$out[] = '---';
$out[] = '';
$out[] = '## How to read this';
$out[] = '';
$out[] = '| Column | What it tells you |';
$out[] = '|---|---|';
$out[] = '| **Column** | The column name. Bold means it is a primary key |';
$out[] = '| **Type** | The MySQL type |';
$out[] = '| **Null** | `-` means NOT NULL. `yes` means the column may be empty, and the meaning column says what empty means |';
$out[] = '| **Default** | What a row gets when nothing is supplied |';
$out[] = '| **Points at** | The foreign key target, and what happens when the parent goes |';
$out[] = '| **What it means** | Why the column exists and what a reader should know about it |';
$out[] = '';
$out[] = 'Two conventions run through the whole schema and are worth knowing before you';
$out[] = 'read any table:';
$out[] = '';
$out[] = '**`organisation_id` is the tenancy boundary.** Almost every table has one, and';
$out[] = 'the `BelongsToOrganisation` trait applies a global scope that matches NOTHING';
$out[] = 'when no organisation context is resolved - not everything. The failure mode of a';
$out[] = 'missing scope is an empty screen somebody investigates, never another';
$out[] = "customer's data.";
$out[] = '';
$out[] = '**`*_by_user_id` columns are `nullOnDelete`.** The record survives the person';
$out[] = 'leaving. An approval that happened still happened, and losing who made it would';
$out[] = 'be worse than showing a departed account.';
$out[] = '';
$out[] = '---';
$out[] = '';
$out[] = '## Contents';
$out[] = '';

foreach ($byModule as $module => $list) {
    $out[] = '**'.$module.'** - '.implode(', ', array_map(static fn ($t) => '['.$t.'](#'.str_replace('_', '-', $t).')', $list));
    $out[] = '';
}

$out[] = '---';
$out[] = '';

foreach ($byModule as $module => $list) {
    $out[] = '# '.$module;
    $out[] = '';

    foreach ($list as $t) {
        $info = $meanings['tables'][$t] ?? [];
        $cols = $tables[$t] ?? [];

        $out[] = '## `'.$t.'`';
        $out[] = '';

        if ($info !== []) {
            $out[] = $info['purpose'];
            $out[] = '';
            $out[] = '| | |';
            $out[] = '|---|---|';
            $out[] = '| **Module** | '.$info['module'].' |';
            $out[] = '| **Introduced** | '.$info['gate'].' |';
            $out[] = '| **Classification** | '.$info['class'].' |';
            $out[] = '| **Personal data** | '.$info['personal'].' |';
            $out[] = '| **Columns** | '.count($cols).' |';
            $out[] = '';

            if (($info['notes'] ?? '') !== '') {
                $out[] = $info['notes'];
                $out[] = '';
            }
        } else {
            $out[] = '_No description recorded. Add one to `tools/data-meanings.php`._';
            $out[] = '';
        }

        $out[] = '| Column | Type | Null | Default | Points at | What it means |';
        $out[] = '|---|---|---|---|---|---|';

        foreach ($cols as $name => $c) {
            $isPk = str_contains($c['type'], 'AUTO_INCREMENT');
            $label = $isPk ? '**'.$name.'**' : '`'.$name.'`';
            $null = $c['nullable'] ? 'yes' : '-';
            $default = $c['default'] === null ? '-' : '`'.$c['default'].'`';
            $points = $fkByColumn[$t.'.'.$name] ?? '-';
            if ($points !== '-') {
                $points = '`'.$points.'`';
            }
            $means = meaningFor($t, $name, $columnMeanings, $meanings['columns']);

            $out[] = '| '.$label.' | `'.$c['type'].'` | '.$null.' | '.$default.' | '.$points.' | '.$means.' |';
        }

        $out[] = '';
    }

    $out[] = '---';
    $out[] = '';
}

$out[] = '## Tables that exist but are not in use';
$out[] = '';
$out[] = 'Four framework tables are created by Laravel and written by nothing in this';
$out[] = 'deployment. They are listed because an empty table that LOOKS like it should';
$out[] = 'have rows is a question somebody will eventually ask.';
$out[] = '';
$out[] = '| Table | Why it is empty | What would change that |';
$out[] = '|---|---|---|';
$out[] = '| `sessions` | Production runs `SESSION_DRIVER=file` (SEC-DEC-049) | Switching the driver to `database`. It then holds IP addresses and user agents, and PDPA-01 scope must include it |';
$out[] = '| `jobs` | Production runs `QUEUE_CONNECTION=sync`, so jobs run inline (CFG-QUEUE-001) | Gate 6, which needs a real queue driver and a running worker |';
$out[] = '| `job_batches` | Same | Same |';
$out[] = '| `failed_jobs` | Same. Nothing is queued, so nothing can fail asynchronously | Same. Payloads must then be assumed to carry personal data |';
$out[] = '';

file_put_contents($root.'/doc/DATA_DICTIONARY.md', implode("\n", $out)."\n");
