<?php

declare(strict_types=1);

/**
 * Renders doc/ENTITY_RELATIONSHIP.md. Included by generate-data-docs.php.
 *
 * The diagrams are Mermaid `erDiagram`, which GitHub renders inline and which
 * is plain ASCII, so it satisfies the writing-style rule as well as being
 * readable as source.
 *
 * It draws one diagram PER MODULE rather than one for everything. A single
 * diagram of 25 tables with 58 foreign keys is a picture nobody reads; five
 * diagrams that each fit on a screen are five pictures somebody does.
 */

/** Cardinality label. Every FK here is many-to-one; nullability decides optionality. */
$rel = static function (array $fk) use ($tables): string {
    $col = $fk['columns'][0] ?? '';
    $nullable = $tables[$fk['table']][$col]['nullable'] ?? false;

    /* parent ||--o{ child  = one to zero-or-more, required parent
     * parent |o--o{ child  = optional parent */
    return $nullable ? '|o--o{' : '||--o{';
};

$frameworkTables = ['cache', 'cache_locks', 'jobs', 'job_batches', 'failed_jobs', 'sessions', 'password_reset_tokens', 'migrations'];

$out = [];
$out[] = '# SemantIQ Entity Relationship Model';
$out[] = '';
$out[] = '**GENERATED. Do not edit this file by hand.**';
$out[] = '';
$out[] = 'Regenerate with:';
$out[] = '';
$out[] = '```text';
$out[] = 'php tools/generate-data-docs.php';
$out[] = '```';
$out[] = '';
$out[] = 'Every relationship below is a real foreign key read from the live database.';
$out[] = 'Nothing here is inferred from a column name.';
$out[] = '';
$out[] = 'Column-level detail is in [DATA_DICTIONARY.md](DATA_DICTIONARY.md).';
$out[] = '';
$out[] = 'Covers '.$generatedFrom.'.';
$out[] = '';
$out[] = '---';
$out[] = '';
$out[] = '## How to read the diagrams';
$out[] = '';
$out[] = '```text';
$out[] = 'PARENT ||--o{ CHILD    the child MUST have a parent';
$out[] = 'PARENT |o--o{ CHILD    the child MAY have a parent (the column is nullable)';
$out[] = '```';
$out[] = '';
$out[] = 'One diagram per module. A single picture of 25 tables and 58 keys is a picture';
$out[] = 'nobody reads.';
$out[] = '';
$out[] = '---';
$out[] = '';
$out[] = '## 1. The shape of the whole thing';
$out[] = '';
$out[] = 'Two tables anchor everything else, and it is worth seeing that before any detail.';
$out[] = '';
$out[] = '**`organisations` is the tenancy root.** Almost every table carries an';
$out[] = '`organisation_id` pointing at it, and the `BelongsToOrganisation` global scope';
$out[] = 'turns that column into the boundary between one customer and the next. With no';
$out[] = 'organisation context resolved the scope matches nothing at all, which is why a';
$out[] = 'missing scope produces an empty screen rather than somebody else\'s data.';
$out[] = '';
$out[] = '**`users` is referenced by almost everything, and is scoped differently.** It is';
$out[] = 'the one scoped table with no global organisation scope, because it is loaded by';
$out[] = 'id on every request and a fail-closed scope there would lock everybody out,';
$out[] = 'including whoever would fix it (SEC-DEC-022). Its tenancy is enforced';
$out[] = 'explicitly instead, on every read path and every mutation.';
$out[] = '';

/* Count how many tables point at each anchor. */
$pointsAtOrg = 0;
$pointsAtUser = 0;
foreach ($foreignKeys as $fk) {
    if ($fk['foreign_table'] === 'organisations') {
        $pointsAtOrg++;
    }
    if ($fk['foreign_table'] === 'users') {
        $pointsAtUser++;
    }
}

$out[] = '| Anchor | Foreign keys pointing at it | What that means |';
$out[] = '|---|---|---|';
$out[] = '| `organisations` | '.$pointsAtOrg.' | The tenancy boundary. Cascade on delete: removing a customer removes their data |';
$out[] = '| `users` | '.$pointsAtUser.' | Attribution. Almost all null on delete: the record survives the person |';
$out[] = '';
$out[] = '---';
$out[] = '';

$section = 2;

foreach ($byModule as $module => $list) {
    if ($module === 'Laravel') {
        continue;
    }

    $out[] = '## '.$section.'. '.$module;
    $out[] = '';
    $section++;

    /* Every FK where either end is in this module. */
    $edges = [];
    foreach ($foreignKeys as $fk) {
        $inModule = in_array($fk['table'], $list, true);
        if (! $inModule) {
            continue;
        }
        $edges[] = $fk;
    }

    $out[] = '```mermaid';
    $out[] = 'erDiagram';

    /* Declare each table with its key columns, so the diagram carries some
     * substance rather than being a box of names. */
    $declared = [];
    foreach ($list as $t) {
        $declared[$t] = true;
    }
    foreach ($edges as $fk) {
        $declared[$fk['foreign_table']] = true;
    }

    foreach (array_keys($declared) as $t) {
        $cols = $tables[$t] ?? [];
        $show = [];
        foreach ($cols as $name => $c) {
            $isPk = str_contains($c['type'], 'AUTO_INCREMENT');
            /* A REAL foreign key, from the database. Not a guess from the name:
             * `users.entra_object_id` ends in `_id` and is not one. */
            $isFk = isset($fkByColumn[$t.'.'.$name]);
            $isInteresting = in_array($name, ['code', 'name', 'key', 'status', 'action', 'version', 'tier', 'domain', 'permission_key'], true);

            if ($isPk || $isFk || $isInteresting) {
                $type = preg_replace('/[ (].*/', '', $c['type']);
                $marker = $isPk ? ' PK' : ($isFk ? ' FK' : '');
                $show[] = '        '.$type.' '.$name.$marker;
            }
        }
        $out[] = '    '.$t.' {';
        foreach (array_slice($show, 0, 9) as $line) {
            $out[] = $line;
        }
        $out[] = '    }';
    }

    foreach ($edges as $fk) {
        $col = $fk['columns'][0] ?? '';
        $out[] = '    '.$fk['foreign_table'].' '.$rel($fk).' '.$fk['table'].' : "'.$col.'"';
    }

    $out[] = '```';
    $out[] = '';

    /* The same edges as a table, because a diagram cannot carry the delete rule. */
    if ($edges !== []) {
        $out[] = '| From | Column | To | On delete | Why |';
        $out[] = '|---|---|---|---|---|';

        foreach ($edges as $fk) {
            $col = $fk['columns'][0] ?? '';
            $onDelete = $fk['on_delete'] ? strtolower(str_replace('_', ' ', $fk['on_delete'])) : 'no action';
            $why = match (true) {
                $fk['foreign_table'] === 'organisations' => 'Tenancy. Removing a customer removes their data',
                str_ends_with($col, '_by_user_id') => 'Attribution. The record outlives the person',
                $fk['foreign_table'] === 'users' => 'Points at a person',
                $fk['foreign_table'] === $fk['table'] => 'Self-referencing',
                default => 'Ownership',
            };
            $out[] = '| `'.$fk['table'].'` | `'.$col.'` | `'.$fk['foreign_table'].'` | '.$onDelete.' | '.$why.' |';
        }

        $out[] = '';
    }

    /* Anything worth saying about this module's shape. */
    $moduleNotes = [
        'Identity' => "**The two access dimensions are two different tables, and that is the point.**\n"
            ."`user_roles` says what somebody may DO in the platform. `domain_entitlements`\n"
            ."says which business data they may SEE. ROLE_MODEL.md section 1 is explicit that\n"
            ."a platform role never implies business data, and keeping them apart is how the\n"
            ."schema enforces it: a System Administrator with no `domain_entitlements` row\n"
            ."reads no Finance figure.\n\n"
            ."**There is no `permissions` table.** `role_permissions.permission_key` holds a\n"
            ."string validated against a catalogue in CODE. A permission an administrator\n"
            .'could invent would be a permission nothing checks (SEC-DEC-028).',
        'Audit' => "**`audit_events` has no foreign key to anything it describes**, and that is\n"
            ."deliberate. `resource_type` and `resource_id` are loose columns, so the trail\n"
            ."survives the thing it describes being deleted - which is exactly when the trail\n"
            ."matters most. `actor_label` captures the actor as text for the same reason.\n\n"
            ."The table is **append only, enforced by two database triggers**. Model hooks\n"
            ."throw as well, but they do not fire on a mass delete, and MySQL has no DENY\n"
            .'(SEC-DEC-037).',
        'Platform' => 'Both tables are OVERRIDE stores. A key with no row reads its catalogue '
            ."default, so a fresh install needs no seeder and a key nobody has touched cannot\n"
            .'drift.',
        'Security' => "`security_policies` is an override store like the Platform pair.\n"
            ."`secret_references` is a register - and it holds no secret. There is no column\n"
            ."that could: the model refuses a credential-shaped string and the form request\n"
            .'refuses one before that.',
        'Governance' => "**The two profile tables are VERSION tables, not settings tables.**\n"
            ."`superseded_by_id` is self-referencing: version 2 points back at the version 1\n"
            ."it replaced, so \"what was in force in March\" stays answerable. An approved row\n"
            ."refuses every update except that supersession (SEC-DEC-065).\n\n"
            ."`personal_data_categories.source_tables` is a JSON list of table names rather\n"
            ."than a foreign key, because it points at TABLES rather than rows. It is the\n"
            .'input to the R1.4c collector coverage test.',
    ];

    if (isset($moduleNotes[$module])) {
        $out[] = $moduleNotes[$module];
        $out[] = '';
    }

    $out[] = '---';
    $out[] = '';
}

/* Every foreign key, in one place. */
$out[] = '## '.$section.'. Every foreign key';
$out[] = '';
$out[] = 'All '.count($foreignKeys).' of them, read from the live database.';
$out[] = '';
$out[] = '| From | Column | To | On delete |';
$out[] = '|---|---|---|---|';

$sorted = $foreignKeys;
usort($sorted, static fn ($a, $b) => [$a['table'], $a['columns'][0] ?? ''] <=> [$b['table'], $b['columns'][0] ?? '']);

foreach ($sorted as $fk) {
    $out[] = '| `'.$fk['table'].'` | `'.($fk['columns'][0] ?? '').'` | `'.$fk['foreign_table'].'` | '
        .($fk['on_delete'] ? strtolower(str_replace('_', ' ', $fk['on_delete'])) : 'no action').' |';
}

$out[] = '';
$out[] = '---';
$out[] = '';
$out[] = '## '.($section + 1).'. What is deliberately NOT a foreign key';
$out[] = '';
$out[] = 'Four references in this schema are not enforced by the database, each for a';
$out[] = 'stated reason. They are listed because an unenforced reference that nobody wrote';
$out[] = 'down looks like an oversight.';
$out[] = '';
$out[] = '| Reference | Why it is not a foreign key |';
$out[] = '|---|---|';
$out[] = '| `audit_events.resource_type` + `resource_id` | The trail must survive the thing it describes being deleted. A foreign key would either block the delete or cascade away the evidence |';
$out[] = '| `role_permissions.permission_key` | There is no `permissions` table. The catalogue is code, so that a permission cannot be invented in the database (SEC-DEC-028) |';
$out[] = '| `system_settings.key`, `feature_flags.key`, `security_policies.key` | Same reasoning. The catalogue decides which keys exist; the table holds overrides only |';
$out[] = '| `personal_data_categories.source_tables` | It points at TABLES, not rows. Validated by the R1.4c coverage test against the live schema instead |';
$out[] = '';

file_put_contents($root.'/doc/ENTITY_RELATIONSHIP.md', implode("\n", $out)."\n");
